INSERT INTO chatyour_toto.`gr_language_strings` (`string_constant`, `string_value`, `string_type`, `skip_update`, `skip_cache`, `language_id`) VALUES
('coin_purchase_packages', 'Coin purchase packages', 'one-line', 0, 0, 1),
('coin_conversions', 'Coin convertions', 'one-line', 0, 0, 1),
('minimum_conversion_value', 'Minimum Conversion Value', 'one-line', 0, 0, 1),
('maximum_conversion_value', 'Maximum conversion value', 'one-line', 0, 0, 1),
('conversions_per_user_per_day', 'The number of conversions per user per day', 'one-line', 0, 0, 1),
('coins_amount_per_statement', 'Coins amount per statement', 'one-line', 0, 0, 1),
('coins_amount_per_private_chat', 'Coins amount per private chat', 'one-line', 0, 0, 1),
('number_of_friends_for_coins', 'Number of friends for coins', 'one-line', 0, 0, 1),
('coins_amount_per_friends', 'Coins amount per friends', 'one-line', 0, 0, 1),
('coins_amount_per_msg_reaction', 'Coins amount per message reaction', 'one-line', 0, 0, 1),
('coins_feature', 'Coins Feature', 'one-line', 0, 0, 1),
('coins_packages', 'Coins Packages', 'one-line', 0, 0, 1),
('price', 'Price', 'one-line', 0, 0, 1),
('active', 'Active', 'one-line', 0, 0, 1),
('purchase_coin_packages', 'Purchase Coin Packages', 'one-line', 0, 0, 1),
('adding_coins_and_control_it', 'Adding coins and control it', 'one-line', 0, 0, 1),
('receive_conversions', 'Receive Conversions', 'one-line', 0, 0, 1),
('add_coins_to_members', 'Add coins to members', 'one-line', 0, 0, 1),
('convert_coins_to_non_friends', 'Convert coins to non friend', 'one-line', 0, 0, 1),
('see_members_coins_balance', 'See members coins balance', 'one-line', 0, 0, 1),
('deduct_coins_from_members', 'Deduct coins from members', 'one-line', 0, 0, 1),
('can_deduct_from_who_can_deduct_coins', 'Can deduct from who can deduct coins', 'one-line', 0, 0, 1),
('ban_member_from_sending_coins', 'Ban member from sending coins', 'one-line', 0, 0, 1),
('ban_member_from_receiving_coins', 'Ban member from receiving coins', 'one-line', 0, 0, 1),
('minimum_value_to_convert_coins', 'Minimum value to convert coins', 'one-line', 0, 0, 1),
('maximum_value_to_convert_coins', 'Maximum value to convert coins', 'one-line', 0, 0, 1),
('available_balance_to_convert_coins', 'Available balance to convert coins', 'one-line', 0, 0, 1),
('allow_conversion', 'Allow conversion', 'one-line', 0, 0, 1),
('coins_log', 'Coins log', 'one-line', 0, 0, 1),
('richest_of_coins_limit', 'Richest of coins limit', 'one-line', 0, 0, 1),
('richest_of_coins', 'Richest of coins', 'one-line', 0, 0, 1),
('delete_coin_actions_log', 'Delete coin actions log', 'one-line', 0, 0, 1),
('payment_info', 'Payment Info', 'one-line', 0, 0, 1),
('bank_name', 'Bank Name', 'one-line', 0, 0, 1),
('iban', 'IBAN', 'one-line', 0, 0, 1),
('swift_code', 'Swift Code', 'one-line', 0, 0, 1),
('buy', 'Buy', 'one-line', 0, 0, 1),
('purchase_requests', 'Purchase Requests', 'one-line', 0, 0, 1),
('status', 'Status', 'one-line', 0, 0, 1),
('coin_purchase_packages', 'شراء باقات الكوينز', 'one-line', 0, 0, 2),
('coin_conversions', 'تحويل الكوينز', 'one-line', 0, 0, 2),
('minimum_conversion_value', 'اقل قيمة للتحويل', 'one-line', 0, 0, 2),
('maximum_conversion_value', 'أعلى قيمة للتحويل', 'one-line', 0, 0, 2),
('conversions_per_user_per_day', 'عدد التحويلات للمستخدم خلال يوم', 'one-line', 0, 0, 2),
('coins_amount_per_statement', 'كوينز مقابل كل جملة على العام', 'one-line', 0, 0, 2),
('coins_amount_per_private_chat', 'كوينز مقابل الدردشة على الخاص', 'one-line', 0, 0, 2),
('number_of_friends_for_coins', 'عدد الاصدقاء مقابل الكوينز', 'one-line', 0, 0, 2),
('coins_amount_per_friends', 'كمية الكوينز مقابل عدد الاصدقاء', 'one-line', 0, 0, 2),
('coins_amount_per_msg_reaction', 'الكوينز مقابل الرياكشن على الرسائل', 'one-line', 0, 0, 2),
('coins_feature', 'خاصية الكوينز', 'one-line', 0, 0, 2),
('coins_packages', 'باقات الكوينز', 'one-line', 0, 0, 2),
('price', 'السعر', 'one-line', 0, 0, 2),
('active', 'فعال', 'one-line', 0, 0, 2),
('purchase_coin_packages', 'شراء باقات الكوينز', 'one-line', 0, 0, 2),
('adding_coins_and_control_it', 'اضافة الكوينز والتحكم بها', 'one-line', 0, 0, 2),
('receive_conversions', 'استقبال التحويلات', 'one-line', 0, 0, 2),
('add_coins_to_members', 'اضافة كوينز للاعضاء', 'one-line', 0, 0, 2),
('convert_coins_to_non_friends', 'تحويل كوينز لاشخاص ليسو اصدقاء', 'one-line', 0, 0, 2),
('see_members_coins_balance', 'رؤية رصيد الكوينز للاعضاء', 'one-line', 0, 0, 2),
('deduct_coins_from_members', 'خصم الكونز من الاعضاء', 'one-line', 0, 0, 2),
('can_deduct_from_who_can_deduct_coins', 'لا يمكن خصم الكونز من الشخص الذي قوم بخصم الكوينز', 'one-line', 0, 0, 2),
('ban_member_from_sending_coins', 'حظر العضو من ارسال الكوينز', 'one-line', 0, 0, 2),
('ban_member_from_receiving_coins', 'حظر العضو من استقبال الكوينز', 'one-line', 0, 0, 2),
('minimum_value_to_convert_coins', 'أقل قيمة لتحويل الكوينز', 'one-line', 0, 0, 2),
('maximum_value_to_convert_coins', 'أعلى قيمة لتحويل الكوينز', 'one-line', 0, 0, 2),
('available_balance_to_convert_coins', 'الرصيد المتاح لتحويل الكوينز', 'one-line', 0, 0, 2),
('allow_conversion', 'السماح بالتحويل', 'one-line', 0, 0, 2),
('coins_log', 'سجل الكوينز', 'one-line', 0, 0, 2),
('richest_of_coins_limit', 'عدد الاغنى بالكوينز', 'one-line', 0, 0, 2),
('richest_of_coins', 'الاغنى بالكوينز', 'one-line', 0, 0, 2),
('delete_coin_actions_log', 'حذف سجل حركات الكوينز', 'one-line', 0, 0, 2),
('payment_info', 'معلومات الدفع', 'one-line', 0, 0, 2),
('bank_name', 'اسم البنك', 'one-line', 0, 0, 2),
('iban', 'IBAN', 'one-line', 0, 0, 2),
('swift_code', 'رمز سويفت', 'one-line', 0, 0, 2),
('buy', 'شراء', 'one-line', 0, 0, 2),
('purchase_requests', 'طلبات الشراء', 'one-line', 0, 0, 2),
('status', 'الحالة', 'one-line', 0, 0, 2),
('send_coins', 'Send Coins', 'one-line', 0, 0, 1),
('send_coins', 'ارسال الكوينز', 'one-line', 0, 0, 2),
('receive_coins', 'Receive Coins', 'one-line', 0, 0, 1),
('receive_coins', 'استقبال الكوينز', 'one-line', 0, 0, 2),
('grant_coins', 'Grant Coins', 'one-line', 0, 0, 1),
('grant_coins', 'منح الكوينز', 'one-line', 0, 0, 2),
('remove_coins', 'Remove Coins', 'one-line', 0, 0, 1),
('remove_coins', 'ازالة الكوينز', 'one-line', 0, 0, 2),
('ban_send_coins', 'Ban Send Coins', 'one-line', 0, 0, 1),
('ban_send_coins', 'حظر ارسال الكوينز', 'one-line', 0, 0, 2),
('ban_receive_coins', 'Ban Receive Coins', 'one-line', 0, 0, 1),
('ban_receive_coins', 'حظر استقبال الكوينز', 'one-line', 0, 0, 2),
('unban_send_coins', 'Unban Send Coins', 'one-line', 0, 0, 1),
('unban_send_coins', 'ازالة حظر ارسال الكوينز', 'one-line', 0, 0, 2),
('unban_receive_coins', 'Unban Receive Coins', 'one-line', 0, 0, 1),
('unban_receive_coins', 'ازالة حظر ارسال الكوينز', 'one-line', 0, 0, 2),
('coins', 'Coins', 'one-line', 0, 0, 1),
('coins', 'الكوينز', 'one-line', 0, 0, 2),
('send_coins_notify', 'Sent you coins', 'one-line', 0, 0, 1),
('send_coins_notify', 'ارسل اليك كوينز', 'one-line', 0, 0, 2),
('grant_coins_notify', 'Grant you coins', 'one-line', 0, 0, 1),
('grant_coins_notify', 'منحك كوينز', 'one-line', 0, 0, 2),
('remove_coins_notify', 'Removed coins from you', 'one-line', 0, 0, 1),
('remove_coins_notify', 'ازال كوينز منك', 'one-line', 0, 0, 2),
('ban_send_coins_notify', 'Banned you from sending coins', 'one-line', 0, 0, 1),
('ban_send_coins_notify', 'حظرك من ارسال الكوينز', 'one-line', 0, 0, 2),
('ban_receive_coins_notify', 'Banned you from receiving coins', 'one-line', 0, 0, 1),
('ban_receive_coins_notify', 'حظرك من استقبال الكوينز', 'one-line', 0, 0, 2),
('unban_send_coins_notify', 'UnBanned you from sending coins', 'one-line', 0, 0, 1),
('unban_send_coins_notify', 'ازال حظر ارسال الكوينز عنك', 'one-line', 0, 0, 2),
('unban_receive_coins_notify', 'UnBanned you from receiving coins', 'one-line', 0, 0, 1),
('unban_receive_coins_notify', 'ازال حظر استقبال الكوينز عنك', 'one-line', 0, 0, 2),
('send_coin_confirmation', 'Are you sure you want to send coins for this user?', 'one-line', 0, 0, 1),
('send_coin_confirmation', 'هل أنت متأكد من انك تريد ارسال الكوينز الى هذا المستخدم؟', 'one-line', 0, 0, 2),
('grant_coin_confirmation', 'Are you sure you want to grant coins to this user?', 'one-line', 0, 0, 1),
('grant_coin_confirmation', 'هل انت متأكد انك تريد ان تمنح كوينز لهذا المستخدم؟', 'one-line', 0, 0, 2),
('remove_coin_confirmation', 'Are you sure you want to remove coins from this user?', 'one-line', 0, 0, 1),
('remove_coin_confirmation', 'هل انت متأكد انك تريد انت تزيل كوينز من هذا المستخدم؟', 'one-line', 0, 0, 2),
('ban_send_coin_confirmation', 'Are you sure you want to ban this user from sending coins?', 'one-line', 0, 0, 1),
('ban_send_coin_confirmation', 'هل انت متأكد انك تريد ان تحظر هذا المستخدم من ارسال الكوينز؟', 'one-line', 0, 0, 2),
('unban_send_coin_confirmation', 'Are you sure you want to unban this user from sending coins?', 'one-line', 0, 0, 1),
('unban_send_coin_confirmation', 'هل انت متأكد انك تريد ان تزيل حظر هذا المستخدم من ارسال الكوينز؟', 'one-line', 0, 0, 2),
('ban_receive_coin_confirmation', 'Are you sure you want to ban this user from receiving coins?', 'one-line', 0, 0, 1),
('ban_receive_coin_confirmation', 'هل انت متأكد انك تريد ان تحظر هذا المستخدم من استقبال الكوينز؟', 'one-line', 0, 0, 2),
('unban_receive_coin_confirmation', 'Are you sure you want to unban this user from receiving coins?', 'one-line', 0, 0, 1),
('unban_receive_coin_confirmation', 'هل انت متأكد انك تريد ان تزيل حظر هذا المستخدم من استقبال الكوينز؟', 'one-line', 0, 0, 2),
('send_coins_button', 'Send Coins', 'one-line', 0, 0, 1),
('send_coins_button', 'ارسال الكوينز', 'one-line', 0, 0, 2),
('grant_coins_button', 'Grant Coins', 'one-line', 0, 0, 1),
('grant_coins_button', 'منح الكوينز', 'one-line', 0, 0, 2),
('remove_coins_button', 'Remove Coins', 'one-line', 0, 0, 1),
('remove_coins_button', 'ازالة الكوينز', 'one-line', 0, 0, 2),
('view_coin_packages', 'View Coin Packages', 'one-line', 0, 0, 1),
('view_coin_packages', 'عرض باقات الكوينز', 'one-line', 0, 0, 2),
('delete_coin_packages', 'Delete Coin Packages', 'one-line', 0, 0, 1),
('delete_coin_packages', 'حذف باقات الكوينز', 'one-line', 0, 0, 2),
('edit_coin_packages', 'Edit Coin Packages', 'one-line', 0, 0, 1),
('edit_coin_packages', 'تحرير باقات الكوينز', 'one-line', 0, 0, 2),
('create_coin_packages', 'Create Coin Packages', 'one-line', 0, 0, 1),
('create_coin_packages', 'اضافة باقات الكوينز', 'one-line', 0, 0, 2)